Fix datepicker styles
vimtor/nuclio-minimalist-clone pull request #62
Opened 2021-03-04 17:12 UTC by fmadueno

Fix datepicker css styles.

2021-03-05 19:15 UTC, vimtor requested changes

2021-03-05 19:15 UTC, vimtor commented on frontend/src/components/date-button/date-button.js
> +// import styles from "./date-button.css";      //do not work. Must use normal .css file
Change `.css` to `.module.css` to use CSS imports with styles

2021-03-05 19:16 UTC, vimtor commented
As you can see the GitHub action failed.
This is because you forgot to format your code.

Fix it until it goes green ✅****

2021-03-08 20:07 UTC, alexcano94 approved these changes

2021-03-09 09:41 UTC, closed without merging